<?php 
require_once './templates/layout/header.phtml';
?>
<!-- L variable items contiene el nombre del item -->
<div class="container overflow-hidden text-center">
    <h2>PRODUCTOS</h2>
    <h3>Seleccione la operacion que desea realizar</h3>
    <table class="table">
    <thead>
      <tr>
        <th scope="col">N° Producto</th>
        <th scope="col">Nombre</th>
        <th scope="col">Precio</th>
        <th scope="col">Descripcion</th>
        <th scope="col">Modificar</th>
        <th scope="col">Eliminar</th>
      </tr>
    </thead>
    <tbody>
    <?php foreach($products as $product) :?>
      <tr>
        <th scope="row"><?php echo$product->id?></th>
        <td><?php echo $product->name ?></td>
        <td><?php echo $product->price ?></td>
        <td><?php echo $product->description?></td>
        <td><a href="<?php echo BASE_URL ?>modificarProducto/<?php echo $product->id ?>" class="btn text-white btn-success">Modificar</a></td>
        <td><a href="<?php echo BASE_URL ?>eliminarProducto/<?php echo $product->id ?>" class="btn btn-danger">Eliminar</a></td>
      </tr>
    <?php endforeach ?>
    </tbody>
  </table>

  <a class="btn btn-primary " href="<?php echo BASE_URL ?>nuevoProducto/<?php echo $product->id ?>">AGREGAR</a>
    
</div>
<?php 
require_once './templates/layout/footer.phtml';
?>