<?php 
require_once './templates/layout/header.phtml';

$isEdit = isset($product);  
?>

<div class="container my-5 p-4 shadow-sm bg-light rounded">
    <h2 class="text-center text-black mb-4"><?= $isEdit ? "Editar producto" : "Agregar nuevo producto" ?></h2>

    <form action="<?= $isEdit ? BASE_URL . 'modificarProducto/' . $product->id : BASE_URL . 'nuevoProducto' ?>" method="POST" enctype="multipart/form-data">
        <div class="row mb-3">
            <div class="col-md-9">
                <div class="form-floating">
                    <input name="name" type="text" class="form-control" id="nameInput" placeholder="Nombre del producto" 
                        value="<?= $isEdit ? $product->name : '' ?>">
                    <label for="nameInput">Nombre del producto</label>
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-floating">
                    <input required name="price" type="number" step="0.01" class="form-control" id="priceInput" placeholder="Precio"
                        value="<?= $isEdit ? $product->price : '' ?>">
                    <label for="priceInput">Precio</label>
                </div>
            </div>
        </div>

        <div class="form-floating mb-3">
            <textarea name="description" class="form-control" placeholder="Descripción" id="descriptionInput" style="height: 100px" required><?= $isEdit ? $product->description : '' ?></textarea>
            <label for="descriptionInput">Descripción</label>
        </div>

        <div class="form-group">
            <label for="imageProduct">Subir Imagen</label>
            <input type="file" class="form-control-file" id="imageProduct" name="image_product" accept="image/jpeg, image/png">
        </div>
        <div><label for="imageProduct">Formatos jpeg-png</label></div>

        <div class="text-center">
            <button type="submit" class="btn btn-primary btn-lg">Guardar</button>
        </div>
    </form>
    <a href="<?php echo BASE_URL; ?>controlarProductos" class="btn btn-primary ms-5 mt-2" id="volver">VOLVER</a>
</div>

<?php 
require_once './templates/layout/footer.phtml';
?>
