<?php require_once './templates/layout/header.phtml' ?>
<?php if ($error): ?>
    <div class='alert alert-danger' role='alert'>
        <?= $error ?>
    </div>
<?php endif ?>
<form method='POST' action='verificarLogin'>
    <div class='form-group'>
        <label for='userName'>Nombre usuario</label>
        <input type='text' class='form-control' name='userName' required>
    </div>
    <div class='form-group'>
        <label for='password'>Password</label>
        <input type='password' class='form-control' name='password' required>
    </div>
    <button type='submit' class='btn btn-primary'>Login</button>
</form>
<?php require_once './templates/layout/footer.phtml' ?>