<?php require './templates/layout/header.phtml';?>
<div class="container overflow-hidden text-center">
  <table class="table">
    <thead>
      <tr>
        <th scope="col">N° Orden</th>
        <th scope="col">Precio</th>
        <th scope="col">----</th>
      </tr>
    </thead>
    <tbody>
    <?php foreach($orders as $order) :?>
      <tr>
        <th scope="row"><?php echo$order->id?></th>
        <td><?php echo $order->total ?></td>
        <td><a href="<?php echo BASE_URL . "verOrden/" . $order->id?>">Ver Completo</a></td>
      </tr>
    <?php endforeach ?>
    </tbody>
  </table>
</div>
<?php require './templates/layout/footer.phtml' ?>
