<?php require './templates/layout/header.phtml' ?>
<!-- echo "<h1>Ordenes</h1>
        <ul>";
        foreach($orders as $order){
            echo "<li> Orden n° $order->id; precio total $order->total <a href='verOrden/$order->id'>Ver Completo</a></li>";
        }
          
        echo "</ul>"; -->
        <div class="container overflow-hidden text-center">
  <!-- Content here -->

<table class="table">
  <thead>
    <tr>
      <th scope="col">N° Orden</th>
      <th scope="col">Precio</th>
      <th scope="col">----</th>
    </tr>
  </thead>
  <tbody>
    <?php foreach($orders as $order) :?>
    <tr>
      <th scope="row"><?php echo$order->id?></th>
      <td><?php echo $order->total ?></td>
      <td><a href="verOrden/<?php echo$order->id?>">Ver Completo</a></td>
    </tr>
    <?php endforeach ?>
  </tbody>
</table>
</div>
<?php require './templates/layout/footer.phtml' ?>
